<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Hasil Ranking SAW</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        
        .header h1 {
            margin: 0;
            color: #333;
        }
        
        .header p {
            color: #666;
            margin: 5px 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        thead {
            background-color: #667eea;
            color: white;
        }
        
        th {
            padding: 12px;
            text-align: left;
            border: 1px solid #ddd;
        }
        
        td {
            padding: 12px;
            border: 1px solid #ddd;
        }
        
        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #999;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Hasil Ranking Sistem Penunjang Keputusan</h1>
        <p>Metode: Simple Additive Weighting (SAW)</p>
        <p>Tanggal: {{ date('d-m-Y H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 8%; text-align: center;">Ranking</th>
                <th style="width: 25%;">Nama Perusahaan</th>
                <!-- Dynamic kolom C1, C2, C3, C4 -->
                @foreach ($kriteria as $index => $krit)
                    <th style="text-align: center; font-size: 9px;">
                        C{{ $index + 1 }}<br>
                        <span style="font-weight: normal;">{{ substr($krit->nama_kriteria, 0, 12) }}</span>
                    </th>
                @endforeach
                <th style="width: 12%; text-align: center;">Skor Akhir</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($results as $item)
                <tr>
                    <td style="text-align: center;">
                        <strong>{{ $item->ranking }}</strong>
                    </td>
                    <td>{{ $item->perusahaan->nama_prs ?? '-' }}</td>
                    <!-- Display C1, C2, C3, C4 (weighted score per kriteria) -->
                    @foreach ($kriteria as $krit)
                        @php
                            $detail = $item->detail_kriteria[$krit->kode_kriteria] ?? null;
                        @endphp
                        <td style="text-align: center; font-size: 10px;">
                            @if ($detail)
                                {{ number_format($detail['weighted'], 4) }}
                            @else
                                -
                            @endif
                        </td>
                    @endforeach
                    <td style="text-align: center;">
                        <strong>{{ number_format($item->skor_akhir, 4) }}</strong>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Sistem Penunjang Keputusan SAW</p>
    </div>
</body>
</html>
